name: Laravel CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pcntl, sqlite, pdo_sqlite
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations (SQLite in-memory)
        run: php artisan migrate --force --database=sqlite

      - name: Run tests
        run: php artisan test --parallel
